/**
 * Provider-free geographic renderers and clearly named schematic diagrams.
 * `geo-maps` remains the compatibility entry point for the original exports.
 */
export * from "./geo-maps";

/** Pure GeoJSON, projection, validation, scale, and clustering utilities. */
export {
  clamp,
  clusterProjectedPoints,
  createClampedScale,
  createGeoLayout,
  featureCollection,
  featureId,
  featureLabel,
  isGeoCoordinate,
  isGeoPointDatum,
  isPlanarPointDatum,
  normalizeFeatureValues,
  normalizeMapPoints,
  normalizeMapRoutes,
  validateFeatureCollection,
  validateSchematicRegions,
  type GeoCoordinate,
  type GeoFeature,
  type GeoFeatureCollection,
  type GeoFeatureValueDatum,
  type GeoGeometry,
  type GeoGeometryCollection,
  type GeoLayout,
  type GeoLayoutFeature,
  type GeoLineStringGeometry,
  type GeoMultiLineStringGeometry,
  type GeoMultiPointGeometry,
  type GeoMultiPolygonGeometry,
  type GeoPointDatum,
  type GeoPointGeometry,
  type GeoPolygonGeometry,
  type GeoProjectionKind,
  type GeoProperties,
  type GeoReferenceLayer,
  type GeoRouteEndpoint,
  type MapPointDatum,
  type MapRouteDatum,
  type MapValidationResult,
  type NormalizedMapPoint,
  type NormalizedMapRoute,
  type PlanarPointDatum,
  type ProjectedPointCluster,
  type SchematicRegion,
} from "./geo-core";
